### PR TITLE
Optimize packing

### PR DESCRIPTION
**Pull request by 0xSachinK**

### CODE REVIEW

**Review by richardliang — COMMENTED** [review]
TODOs:
- Solidity verification 
- Proving key gen
- Update tests
- Docs

**Comment by 0xSachinK** [comment]
Tests done.

TODOs:
- Solidity verification 
- Proving key gen

**Comment by 0xSachinK** [comment]
Solidity verification done.
Key generation done.

**Comment by 0xSachinK** [comment]
Done generation and upload vkey.json

**Pull request merged**
